#!/bin/bash --login
#SBATCH --output=log.maity
#SBATCH -p multinode
#SBATCH -N 3
#SBATCH -n 120
#SBATCH -t 6-0

export OMP_NUM_THREADS=$SLURM_NTASKS
module load openfoam/v2212-foss-2021a
source $FOAM_BASH

rm -r constant/polyMesh
rm -r constant/fluid/polyMesh
blockMesh
mv constant/polyMesh constant/fluid

rm -r 0 proc*
cp -r orig.0 0
setExprFields -region fluid
initAlphaField -region fluid

decomposePar -allRegions

mpirun mulesGradFoam -parallel
