/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | www.openfoam.com
     \\/     M anipulation  |
-------------------------------------------------------------------------------
    Copyright (C) 2011-2016 OpenFOAM Foundation
    Copyright (C) 2017 OpenCFD Ltd.
		Copyright (C) 2023 Jakub Cranmer <jakub@posteo.net>
-------------------------------------------------------------------------------
License
    This file is part of interMultiKFoam.

    interMultiKFoam is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    interMultiKFoam is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with interMultiKFoam.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/
const wordList solidNames(rp["solid"]);

PtrList<fvMesh> solidRegions(solidNames.size());

forAll(solidNames, i)
{
  Info<< "Create solid mesh for region " << solidNames[i]
      << " for time = " << runTime.timeName() << nl << endl;

  solidRegions.set
    (
     i,
     new fvMesh
     (
      IOobject
      (
       solidNames[i],
       runTime.timeName(),
       runTime,
       IOobject::MUST_READ
       )
      )
     );

  // Force calculation of geometric properties to prevent it being done
  // later in e.g. some boundary evaluation
  //(void)solidRegions[i].weights();
  //(void)solidRegions[i].deltaCoeffs();
}
